[package]
name = "sui-core"
version = "0.1.0"
edition = "2021"

[dependencies]
# Async runtime
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

# Cryptography
ed25519-dalek = "2.0"
sha2 = "0.10"
blake2 = "0.10"
rand = "0.8"

# Storage
rocksdb = "0.21"
lru = "0.10"

# Network
libp2p = { version = "0.51", features = ["full"] }

# Move VM
move-core-types = { git = "https://github.com/move-language/move", rev = "main" }
move-binary-format = { git = "https://github.com/move-language/move", rev = "main" }
move-vm-runtime = { git = "https://github.com/move-language/move", rev = "main" }

# Utilities
thiserror = "1.0"
anyhow = "1.0"
log = "0.4"
tracing = "0.1"
hex = "0.4"

[dev-dependencies]
tempfile = "3.8"